FROM node:16.10-alpine as builder
ARG BASE_HREF
RUN mkdir -p /app
WORKDIR /app
COPY package.json /app
COPY package-lock.json /app



RUN npm install
COPY . /app/
RUN  npm run build -- --configuration production --aot
##RUN npm run build -- --prod --aot --base-href ./
##RUN npm run build -- --prod --aot



FROM nginx
EXPOSE 80
COPY --from=builder /app/dist/ /usr/share/nginx/html/




